/*
Copyright 2021 wz123456.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	gpusharev1 "gpushare/api/gpushare/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualPods implements VirtualPodInterface
type FakeVirtualPods struct {
	Fake *FakeGpushareV1
	ns   string
}

var virtualpodsResource = schema.GroupVersionResource{Group: "gpushare.imiss.gpushare", Version: "v1", Resource: "virtualpods"}

var virtualpodsKind = schema.GroupVersionKind{Group: "gpushare.imiss.gpushare", Version: "v1", Kind: "VirtualPod"}

// Get takes name of the virtualPod, and returns the corresponding virtualPod object, and an error if there is any.
func (c *FakeVirtualPods) Get(ctx context.Context, name string, options v1.GetOptions) (result *gpusharev1.VirtualPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtualpodsResource, c.ns, name), &gpusharev1.VirtualPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*gpusharev1.VirtualPod), err
}

// List takes label and field selectors, and returns the list of VirtualPods that match those selectors.
func (c *FakeVirtualPods) List(ctx context.Context, opts v1.ListOptions) (result *gpusharev1.VirtualPodList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtualpodsResource, virtualpodsKind, c.ns, opts), &gpusharev1.VirtualPodList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &gpusharev1.VirtualPodList{ListMeta: obj.(*gpusharev1.VirtualPodList).ListMeta}
	for _, item := range obj.(*gpusharev1.VirtualPodList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualPods.
func (c *FakeVirtualPods) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtualpodsResource, c.ns, opts))

}

// Create takes the representation of a virtualPod and creates it.  Returns the server's representation of the virtualPod, and an error, if there is any.
func (c *FakeVirtualPods) Create(ctx context.Context, virtualPod *gpusharev1.VirtualPod, opts v1.CreateOptions) (result *gpusharev1.VirtualPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtualpodsResource, c.ns, virtualPod), &gpusharev1.VirtualPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*gpusharev1.VirtualPod), err
}

// Update takes the representation of a virtualPod and updates it. Returns the server's representation of the virtualPod, and an error, if there is any.
func (c *FakeVirtualPods) Update(ctx context.Context, virtualPod *gpusharev1.VirtualPod, opts v1.UpdateOptions) (result *gpusharev1.VirtualPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtualpodsResource, c.ns, virtualPod), &gpusharev1.VirtualPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*gpusharev1.VirtualPod), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualPods) UpdateStatus(ctx context.Context, virtualPod *gpusharev1.VirtualPod, opts v1.UpdateOptions) (*gpusharev1.VirtualPod, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(virtualpodsResource, "status", c.ns, virtualPod), &gpusharev1.VirtualPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*gpusharev1.VirtualPod), err
}

// Delete takes name of the virtualPod and deletes it. Returns an error if one occurs.
func (c *FakeVirtualPods) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(virtualpodsResource, c.ns, name), &gpusharev1.VirtualPod{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualPods) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtualpodsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &gpusharev1.VirtualPodList{})
	return err
}

// Patch applies the patch and returns the patched virtualPod.
func (c *FakeVirtualPods) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *gpusharev1.VirtualPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualpodsResource, c.ns, name, pt, data, subresources...), &gpusharev1.VirtualPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*gpusharev1.VirtualPod), err
}
